### ISSUE TITLE
Issue on Integration Setup

### ISSUE THREAD

**Issue by zacharyasmith** [kdeyev/eyeonwater#104]
```
Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 8:52:55 AM (2 occurrences)
Last logged: 8:54:23 AM

Error setting up entry ---REDACTED--- for eyeonwater
Traceback (most recent call last):
  File "/config/lsiopy/lib/python3.11/site-packages/pyonwater/meter_reader.py", line 115, in read_historical_data_one_day
    data = HistoricalData.parse_raw(raw_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 549, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for HistoricalData
timeseries -> 4928193028058372026,0 -> series -> 9 -> display_unit
  field required (type=value_error.missing)
timeseries -> 4928193028058372026,0 -> series -> 9 -> bill_read
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/eyeonwater/coordinator.py", line 43, in read_meters
    await meter.read_historical_data(
  File "/config/lsiopy/lib/python3.11/site-packages/pyonwater/meter.py", line 64, in read_historical_data
    historical_data = await self._reader.read_historical_data(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/pyonwater/meter_reader.py", line 79, in read_historical_data
    statistics += await self.read_historical_data_one_day(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/pyonwater/meter_reader.py", line 118, in read_historical_data_one_day
    raise EyeOnWaterAPIError(msg) from e
pyonwater.exceptions.EyeOnWaterAPIError: Unexpected EOW response 2 validation errors for HistoricalData
timeseries -> 4928193028058372026,0 -> series -> 9 -> display_unit
  field required (type=value_error.missing)
timeseries -> 4928193028058372026,0 -> series -> 9 -> bill_read
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/__init__.py", line 52, in async_setup_entry
    await eye_on_water_data.read_meters(days_to_load=30)
  File "/config/custom_components/eyeonwater/coordinator.py", line 48, in read_meters
    raise UpdateFailed(error) from error
homeassistant.helpers.update_coordinator.UpdateFailed: Unexpected EOW response 2 validation errors for HistoricalData
timeseries -> 4928193028058372026,0 -> series -> 9 -> display_unit
  field required (type=value_error.missing)
timeseries -> 4928193028058372026,0 -> series -> 9 -> bill_read
  field required (type=value_error.missing)

```

**Comment by kdeyev** [comment]
Should be fixed here: https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.6
