### ISSUE TITLE
Detected blocking call to open with args

### ISSUE THREAD

**Issue by bsp9493** [kdeyev/eyeonwater#113]
Not sure if this got reopened

Issue is back with release version….

Switched back to beta

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 6:00:36 PM (1 occurrences)
Last logged: 6:00:36 PM

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/US/Pacific', 'rb') inside the event loop by custom integration 'eyeonwater' at custom_components/eyeonwater/coordinator.py, line 43: await meter.read_historical_data( (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please report it to the author of the 'eyeonwater' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in async_refresh await self._async_refresh(log_failures=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data return await self.update_method() File "/config/custom_components/eyeonwater/__init__.py", line 52, in async_update_data await eye_on_water_data.read_meters(days_to_load=3) File "/config/custom_components/eyeonwater/coordinator.py", line 43, in read_meters await meter.read_historical_data(

**Comment by kdeyev** [comment]
Hi @bsp9493,
Thank you for reopening. I apologize I'm super busy with my main job right now: will try to get rid of this warning later.
This warning message is pretty harmless, and can be safely ignored.
btw, [v2.5.12-beta.1](https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.12-beta.1) and [v2.5.12](https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.12) are practically the same source code, I will be very surprised if these versions behave differently.

**Comment by bsp9493** [comment]
No worries…I figured life took precedence, appreciate the work.I swapped back and forth a few times over a couple times to be sure:(dOn Oct 22, 2024, at 7:27 AM, Konstantin Deev ***@***.***> wrote:﻿
Hi @bsp9493,
Thank you for reopening. I apologize I'm super busy with my main job right now: will try to get rid of this warning later.
This warning message is pretty harmless, and can be safely ignored.
btw, v2.5.12-beta.1 and v2.5.12 are practically the same source code, I will be very surprised if these versions behave differently.

**Comment by arpitgupta** [comment]
fyi still see this in latest HA + eye on water 2.5.12

```
2024-12-21 07:02:10.942 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.13/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'eyeonwater' at custom_components/eyeonwater/coordinator.py, line 43: await meter.read_historical_data( (offender: /usr/local/lib/python3.13/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please report it to the author of the 'eyeonwater' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 355, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/eyeonwater/__init__.py", line 52, in async_update_data
    await eye_on_water_data.read_meters(days_to_load=3)
  File "/config/custom_components/eyeonwater/coordinator.py", line 43, in read_meters
    await meter.read_historical_data(
```

**Comment by kdeyev** [comment]
Could you please try [v2.5.12-beta.1](https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.12-beta.1)?
I monitor this version on my setup and it seems to work as expected.

**Comment by e2thenegpii** [comment]
I can confirm that installing pyonwater 0.3.11 in my home-assistant deployment and a service restart resolved this warning.

**Comment by kdeyev** [comment]
Closing the issue
