### ISSUE TITLE
Error Setting Up - Validation Errors

### ISSUE THREAD

**Issue by BaldEagle94** [kdeyev/eyeonwater#118]
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 4:45:11 PM (2 occurrences)
Last logged: 6:43:06 PM

Error setting up entry xxxxxx@xxxxxx.xx for eyeonwater
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyonwater/meter_reader.py", line 48, in read_meter_info
    meter_info = MeterInfo.parse_obj(meters[0]["_source"])
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 526, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.13/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for MeterInfo
register_0 -> flags
  field required (type=value_error.missing)
register_0 -> latest_read
  field required (type=value_error.missing)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/__init__.py", line 45, in async_setup_entry
    await eye_on_water_data.setup()
  File "/config/custom_components/eyeonwater/coordinator.py", line 35, in setup
    self.meters = await self.account.fetch_meters(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyonwater/account.py", line 67, in fetch_meters
    meter_info = await reader.read_meter_info(client)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyonwater/meter_reader.py", line 51, in read_meter_info
    raise EyeOnWaterAPIError(msg) from e
pyonwater.exceptions.EyeOnWaterAPIError: Unexpected EOW response 2 validation errors for MeterInfo
register_0 -> flags
  field required (type=value_error.missing)
register_0 -> latest_read
  field required (type=value_error.missing) with payload {'linked_device_id': ['NA.Meter.5213922784682119225.180270023.0'], 'updated': 0, 'service_address': '471  W IH 45 FAIRFIELD 75840 TX US', 'last_updated': '2024-12-30T20:23:42.606973', 'service': {'class_code_normalized': '', 'route': '10', 'active': True, 'class_code': 'C', 'service_type': 'W', 'service_id': '02', 'start_date': '2019-05-23T04:59:59', 'service_point_uuid': '5213922784743476939', 'cycle': '01'}, 'alerts': {'leak_alert': {'alert_type': 'CONTINUOUS_FLOW', 'name': 'Continuous flow', 'residential_user_name': 'xxxxx@xxxxx.xx', 'date_updated': None, 'alert_uuid': '5215103647908912379', 'state': 'active', 'date_created': '2022-01-07T20:52:28', 'creator_user_uuid': '5213922784746653288'}}, 'account': {'status': '', 'first_name': '', 'billing_address': '105 W FM 27', 'billing_city': 'FAIRFIELD', 'account_uuid': '5213922784743476908', 'billing_address_2': '', 'full_name': 'I 45 WATER YARD', 'email': '', 'phone': '', 'portal_status': '', 'last_name': '', 'account_id': '10-xxxx-01', 'class_code': 'C', 'billing_address_3': '', 'person_id': '', 'date_created': '2019-05-22T13:21:58', 'account_billing_cycle': '', 'billing_zip_code': '75840', 'billing_country': 'US', 'billing_state': 'TX', 'eyeonwater': 'Yes'}, 'meter': {'has_endpoint': False, 'meter_uuid': '5213922784743476947', 'fluid_type': 'Water', 'timezone': 'US/Central', 'geocode_status': 1, 'geo': '31.713079,-96.178189', 'note': '', 'meter_size_unit': 'INCHES', 'alert_code': 0, 'gas_pressure_compensation': 1.0, 'latitude': '31.713079', 'serial_number': '180270023', 'type': 'W', 'meter_size_desc': '2"', 'is_compound': 'No', 'service_type': 'W', 'meter_id': '180270023', 'pit_type': 'Unspecified', 'meter_spec_uuid': '5213922784743476952', 'manufacturer': 'Badger Meter', 'has_valve': False, 'has_sensor': False, 'gas_sub_count': 1, 'notes': {'count': 0}, 'meter_size': 2.0, 'install_date': '2019-05-17T04:59:59', 'longitude': '-96.178189', 'model': 'BADGER', 'sequence_number': 84}, 'device_id': 'BEACON.Service.5213922784682119225.10-0750-01.02', 'service_agreement': {'service_agreement_uuid': '5213922784743476977', 'start_date': '2019-05-23T04:59:59'}, 'version': '2', 'user': {'user_uuid': '5213922784746653288', 'user_name': 'xxxx@xxxxx.xx', 'date_created': '2019-06-05T23:24:57'}, 'groups': {'irrigation': 'No', 'continuous_flow': 'No', 'is_irrigatable': 'No', 'disable_valve_shutoff': 'No'}, 'register_0': {'meter_size': 2.0, 'high_read_limit': 1704, 'gas_sub_count': 1, 'meter_size_desc': '2"', 'low_read_limit': 1524, 'utility_use_1': '', 'utility_use_2': '', 'meter_size_unit': 'INCHES', 'endpoint_type': '', 'gas_pressure_compensation': 1.0, 'register_number': 'single', 'resolution': 0.1, 'model': 'BADGER', 'unit': 'GAL'}, 'location_name': 'I 45 WATER YARD', 'utility_uuid': '5213922784682119225', 'utility': {'fluid_barrel_billing_unit': 'FLUID_BARREL', 'cm_billing_unit': 'CM', 'cf_billing_unit': 'CCF', 'type': 'NORMAL', 'utility_name': 'CITY OF FAIRFIELD', 'eow_service_selector': 'NONE', 'gas_cf_billing_unit': 'CF', 'eow_type': 'CLASSIC', 'oil_barrel_billing_unit': 'OIL_BARREL', 'date_created': '2018-11-04T22:57:43', 'gal_billing_unit': 'G100', 'gas_cm_billing_unit': 'CM', 'utility_uuid': '5213922784682119225', 'imp_billing_unit': 'Imp1'}, 'location_id': '0010000750', 'asset_type': 'Service', 'location': {'city': 'FAIRFIELD', 'parcel_number': '', 'location_name': 'I 45 WATER YARD', 'parity': 'O', 'country': 'US', 'route': '10', 'geocode_status': 1, 'zip_code': '75840', 'longitude': '-96.178189', 'display_address_3': '', 'state': 'TX', 'location_uuid': '5213922784743476919', 'county_name': '', 'latitude': '31.713079', 'display_address_2': '', 'location_id': '0010000750', 'display_address': '471  W IH 45', 'display_street_name': '', 'cycle': '01'}}

**Comment by whiskthecat** [comment]
I am also getting "Error setting up" after updating to the latest released but the last line of my log is
`AttributeError: type object 'MeterInfo' has no attribute 'model_validate'`

**Comment by kdeyev** [comment]
Hi, thank you for reporting the issue.
The payload you attached loos slightly not regular. Could you please confirm that this is the payload you get from eyeonwater?

**Comment by BaldEagle94** [comment]
Yes, this is the payload from eyeonwater.   I redacted (xxxxxx) my username and account number.  I do have multiple meters linked to my account.

**Comment by kdeyev** [comment]
Hm, then your payload is slightly different from everything I saw so far. The eyeonwater API is not official and I've practically done reverse engineering of it. Clearly my assumptions about this were wrong: latest_read and flag flags are not mandatory.
The fix may take a bit of time and will require collaboration. Please let me know if you are ready to have a reverse-engineering journey
