### ISSUE TITLE
Unsupported Units CF

### ISSUE THREAD

**Issue by randomstring** [kdeyev/eyeonwater#13]
I'm in the US (Washington state to be exact) and it look like CF (cubic feet) is not a supported unit. Complete error message included below. The website and my phone app report volume in gallons, but it looks like the meters are natively reporting CF. This is with the most recent code base.

```
Logger: homeassistant
Source: custom_components/eyeonwater/eow.py:155
Integration: EyeOnWater ([documentation](https://github.com/kdeyev/eyeonwater))
First occurred: 9:42:02 PM (2 occurrences)
Last logged: 9:44:47 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/eyeonwater/sensor.py", line 85, in _state_update
    self._state = self.meter.reading
  File "/config/custom_components/eyeonwater/eow.py", line 155, in reading
    raise EyeOnWaterAPIError(f"Unsupported measurement unit: {read_unit}")
custom_components.eyeonwater.eow.EyeOnWaterAPIError: Unsupported measurement unit: CF
```

**Comment by kdeyev** [comment]
Fixed. Please update and verify.
Thank you for reaching out!

**Comment by randomstring** [comment]
Yes, this fixed it. Thanks for the quick response.
