### ISSUE TITLE
Error setting up entry

### ISSUE THREAD

**Issue by mkosmo** [kdeyev/eyeonwater#17]
Howdy-

Since updating to HA Core 2023.5.0, this component is no longer loading.  The integration fails with this error:

```
Error setting up entry mkosmo@gmail.com for eyeonwater

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eyeonwater/__init__.py", line 72, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

Additional logs:

```
2023-05-04 10:24:00.375 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration eyeonwater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-04 10:24:25.125 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'influxdb', 'input_select', 'met', 'automation', 'config', 'person', 'homeassistant_hardware', 'stream', 'sharkiq', 'sun', 'script', 'input_button', 'zwave_js', 'timer', 'trace', 'brother', 'sensor', 'homekit_controller', 'conversation', 'system_health', 'scene', 'nws', 'auto_backup', 'alarmo', 'radio_browser', 'stt', 'esphome', 'input_datetime', 'diagnostics', 'myq', 'cast', 'schedule', 'accuweather', 'eyeonwater', 'counter', 'energy', 'history', 'ffmpeg', 'device_automation', 'co2signal', 'tplink', 'search', 'media_source', 'homeassistant_alerts', 'input_text', 'mqtt', 'zha', 'hacs', 'fontawesome', 'opensprinkler', 'auth', 'file_upload', 'persistent_notification', 'map', 'zone', 'tts', 'waze_travel_time', 'adaptive_lighting', 'analytics', 'assist_pipeline', 'logbook', 'tasmota', 'homekit', 'unifi', 'input_number', 'smart_meter_texas', 'image_upload', 'blueprint', 'roku', 'tag', 'application_credentials', 'mobile_app', 'lovelace', 'default_config', 'input_boolean', 'ibeacon', 'hardware', 'homeassistant_yellow', 'repairs', 'my', 'bluetooth_adapters', 'onboarding', 'panel_custom', 'notify'}
2023-05-04 10:24:25.245 INFO (MainThread) [homeassistant.setup] Setting up eyeonwater
2023-05-04 10:24:25.246 INFO (MainThread) [homeassistant.setup] Setup of domain eyeonwater took 0.0 seconds
2023-05-04 10:24:30.823 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry mkosmo@gmail.com for eyeonwater
File "/config/custom_components/eyeonwater/__init__.py", line 72, in async_setup_entry
```

**Comment by kdeyev** [comment]
@mkosmo  Howdy howdy :-)
Thank you for the notification!
Yes, I see literally the same problem after the HA update on my end.
I'll take care of it ASAP.

BTW, I see a few more integrations are broken. So it seems that the latest HA got some non-backward-compatible changes.
Anyways, I'll let you know when it's fixed

**Comment by kdeyev** [comment]
@mkosmo 
Fixed

**Comment by mkosmo** [comment]
I can confirm that it loaded.  Thank you so much!
