### ISSUE TITLE
Unsupported measurement unit error

### ISSUE THREAD

**Issue by jeangot** [kdeyev/eyeonwater#18]
Hello,
I have just installed this Integration. It is connecting properly to the Eye on water server and created 2 sensors, one for my meter and one for leak detection. However both sensors show unavailable, and after enabling debug logs, I find the following error:

```


Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 262, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/eyeonwater/sensor.py", line 85, in _state_update
    self._state = self.meter.reading
                  ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/eow.py", line 158, in reading
    raise EyeOnWaterAPIError(f"Unsupported measurement unit: {read_unit}")
custom_components.eyeonwater.eow.EyeOnWaterAPIError: Unsupported measurement unit: 10 GAL

```

I am not familiar enough with HomeAssistant to know if the problem could be that it s getting GAL and only understands gal. I tried changing the code to convert the value to lowercase to see if that helped, but wasn't successful in doing that. Any pointers would be appreciated.

**Comment by kdeyev** [comment]
Fixed. Please, update and try again.

**Comment by jeangot** [comment]
Thank you very much. I confirm that it is working now.
