### ISSUE TITLE
Cubic_meter missing unit of measure

### ISSUE THREAD

**Issue by bsp9493** [kdeyev/eyeonwater#21]
Logger: homeassistant
Source: custom_components/eyeonwater/eow.py:127 
Integration: EyeOnWater ([documentation](https://github.com/kdeyev/eyeonwater)) 
First occurred: July 13, 2023 at 8:10:55 PM (543 occurrences) 
Last logged: 5:22:40 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 262, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/eyeonwater/sensor.py", line 85, in _state_update
    self._state = self.meter.reading
                  ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/eow.py", line 127, in reading
    raise EyeOnWaterAPIError(f"Unsupported measurement unit: {read_unit}")
custom_components.eyeonwater.eow.EyeOnWaterAPIError: Unsupported measurement unit: CUBIC_METER

**Comment by kdeyev** [comment]
fixed

**Comment by bsp9493** [comment]
Thanx!That did the trick… working now:)dOn Jul 16, 2023, at 11:53 AM, Konstantin Deev ***@***.***> wrote:﻿
Closed #21 as completed.
