### ISSUE TITLE
Error Setting up binary_sensor.eyeonwater

### ISSUE THREAD

**Issue by arpitgupta** [kdeyev/eyeonwater#25]
```
2023-08-02 16:50:48.295 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.eyeonwater
2023-08-02 16:50:48.296 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up eyeonwater platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
    sensors.append(EyeOnWaterSensor(meter, coordinator))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/sensor.py", line 50, in __init__
    sensors.append(EyeOnWaterBinarySensor(meter, coordinator, description))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is using the latest release

**Comment by disforw** [comment]
This has been resolved in latest release
