### ISSUE TITLE
Version 1.1 errors after a reboot

### ISSUE THREAD

**Issue by lsellens** [kdeyev/eyeonwater#27]
I noticed after updating to 1.1 that Everytime I reboot my system eyeonwater will not launch. If I hit restart addon it will then successfully launch. Here is the error I get in the log.

Error while setting up eyeonwater platform for sensor
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.11.4/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/eyeonwater/sensor.py", line 29, in async_setup_entry
    sensors.append(EyeOnWaterSensor(meter, coordinator))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/dietpi_userdata/homeassistant/custom_components/eyeonwater/sensor.py", line 51, in __init__
    name=f"Water Meter {meter.meter_info['meter_id']}",
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'meter_id'

**Comment by lsellens** [comment]
Same issue with 1.2

**Comment by disforw** [comment]
I realized that in cleaning up the code I needed to make a breaking change that would require removing and readding the integration.

**Comment by lsellens** [comment]
@disforw I did remove and reinstall the integration. This is happening after.

**Comment by kdeyev** [comment]
@disforw I'm also facing this issue. It seems to be some kind of race condition.

**Comment by disforw** [comment]
I am not able to recreate this, but it could be that I'm testing, adding, removing, deleting daily. Could it be a need for reauth?

**Comment by kdeyev** [comment]
I'm just restarting the HA and after restart, I see the same problem and the same logs.
Reloading the integration fixes it.
I'm trying to localize the problem

**Comment by kdeyev** [comment]
Ok, I found it
```
import aiohttp
import asyncio
import datetime

from eow import Account, Client, Meter

async def main():
    account = Account(eow_hostname="eyeonwater.com", username="...", password="...", metric_measurement_system=False)
    websession = aiohttp.ClientSession()
    client = Client(websession=websession, account=account)

    await client.authenticate()
        
    meters = await account.fetch_meters(client=client)
    print(f"{len(meters)} meters found")
    for meter in meters:
        print('meter_id' in meter.meter_info)
        await meter.read_meter(client=client)
        print('meter_id' in meter.meter_info)
        print(f"meter {meter.meter_uuid} shows {meter.reading}")

    await websession.close()
       

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```
The content of meter info is different before and after the read_meter function call.
We should rely only on the content after read_meter, since this one is getting updated periodically.

**Comment by disforw** [comment]
Right, I looked at this to try and grab more device info besides the uid and unique name. Usually, devices have more customized date (ie: model number, firmware version, manufacturer, ect…). Can we run an update before registering the device?
https://developers.home-assistant.io/docs/device_registry_index/

**Comment by kdeyev** [comment]
It's definitely a race condition, but I cannot understand where.
I've added a long operation in the main async_setup_entry and it mitigated the problem (or hide it).
Anyway, my PR for historical data is ready for review and I've released a beta version for testing.

**Comment by lsellens** [comment]
Error seems to be fixed with v2.0
Thanks!
