### ISSUE TITLE
KeyError: recorder_instance [SOLVED]

### ISSUE THREAD

**Issue by disforw** [kdeyev/eyeonwater#29]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/__init__.py", line 48, in async_setup_entry
    await eye_on_water_data.import_historical_data(days_to_load=30)
  File "/config/custom_components/eyeonwater/coordinator.py", line 80, in import_historical_data
    async_import_statistics(self.hass, metadata, statistics)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 2146, in async_import_statistics
    _async_import_statistics(hass, metadata, statistics)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 2126, in _async_import_statistics
    get_instance(hass).async_import_statistics(metadata, statistics, Statistics)
    ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 744, in get_instance
    instance: Recorder = hass.data[DATA_INSTANCE]
                         ~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'recorder_instance'

**Comment by disforw** [comment]
I am adding this for my own reminder.

if you are receiving this error, it is because you are not loading the “default_config” in your configuration.yaml (like I am in my dev environment).
Only the default configuration allows for recorder and therefore statistics.

**Comment by disforw** [comment]
Turns out, if default_config is not enabled, statistics are not enabled. Therefore, calls to the recorder are seen as critical failure. We should build in a switch variable where if the call for adding statistics from the init fail, then don’t add them in the updates.
