### ISSUE TITLE
multiple database issues 

### ISSUE THREAD

**Issue by bsp9493** [kdeyev/eyeonwater#92]
As well as the other issues recently reported, also noticing these 3 database issues which I am guessing may be related 

current version of home assistant
current version of eyonwater

**THIS ERROR
Logger: homeassistant.components.recorder.util
Source: components/recorder/util.py:139
Integration: Recorder (documentation, issues)
First occurred: January 29, 2024 at 5:00:10 PM (2 occurrences)
Last logged: 7:00:10 AM

Error executing query: (MySQLdb.IntegrityError) (1062, "Duplicate entry '499-1706572800' for key 'ix_statistics_statistic_id_start_ts'") [SQL: INSERT INTO statistics (created, created_ts, metadata_id, start, start_ts, mean, min, max, last_reset, last_reset_ts, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s, ... 3933 characters truncated ... s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING statistics.id, statistics.id AS id__1] [parameters: (None, 1706576410.577547, 28, None, 1706572800.0, 3195.232080623055, 1218.0, 10613.0, None, None, None, None, None, 1706576410.5778189, 29, None, 1706572800.0, 0.14725605999999997, 0.14725606, 0.14725606, None, None, None, None, None, 1706576410.5779796, 31, None, 1706572800.0, 5.8999999999999995, 5.9, 5.9, None, None, None, None, None, 1706576410.578151, 32, None, 1706572800.0, 31.89257960794444, 26.7, 38.6, None, None, None, None, None, 1706576410.5783548 ... 884 parameters truncated ... 69.3626, 69.3535, None, 1706576410.5904734, 492, None, 1706572800.0, 2.1000000000000005, 2.1, 2.1, None, None, None, None, None, 1706576410.5906467, 493, None, 1706572800.0, None, None, None, None, None, 4.6152, 4.6152, None, 1706576410.5908117, 499, None, 1706572800.0, None, None, None, None, None, 723.991, 0.25900000000001455, None, 1706576410.590975, 515, None, 1706572800.0, None, None, None, None, 1706554710.865161, 2.44160729999985, 627.3264551400002)] (Background on this error at: https://sqlalche.me/e/20/gkpj)
Error executing query: (MySQLdb.IntegrityError) (1062, "Duplicate entry '499-1706623200' for key 'ix_statistics_statistic_id_start_ts'") [SQL: INSERT INTO statistics (created, created_ts, metadata_id, start, start_ts, mean, min, max, last_reset, last_reset_ts, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s, ... 3833 characters truncated ... s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING statistics.id, statistics.id AS id__1] [parameters: (None, 1706626810.5791802, 28, None, 1706623200.0, 2321.116250138889, 699.9999999999999, 5398.0, None, None, None, None, None, 1706626810.5794628, 29, None, 1706623200.0, 0.14725605999999997, 0.14725606, 0.14725606, None, None, None, None, None, 1706626810.5796165, 31, None, 1706623200.0, 5.8999999999999995, 5.9, 5.9, None, None, None, None, None, 1706626810.5797615, 32, None, 1706623200.0, 31.094835868972222, 27.5, 39.1, None, None, None, None, None, 1706626810.5799015 ... 860 parameters truncated ... 69.6136, 69.6045, None, 1706626810.5989528, 492, None, 1706623200.0, 2.1000000000000005, 2.1, 2.1, None, None, None, None, None, 1706626810.599085, 493, None, 1706623200.0, None, None, None, None, None, 4.6442, 4.6442, None, 1706626810.5992107, 499, None, 1706623200.0, None, None, None, None, None, 723.991, 0.25900000000001455, None, 1706626810.5993323, 515, None, 1706623200.0, None, None, None, None, 1706554710.865161, 6.03138689999953, 630.91623474)] (Background on this error at: https://sqlalche.me/e/20/gkpj)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1062, "Duplicate entry '499-1706572800' for key 'ix_statistics_statistic_id_start_ts'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 139, in session_scope
    yield session
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 477, in compile_statistics
    modified_statistic_ids = _compile_statistics(
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 573, in _compile_statistics
    session.flush()  # populate the ids of the new StatisticsShortTerm rows
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry '499-1706572800' for key 'ix_statistics_statistic_id_start_ts'")
[SQL: INSERT INTO statistics (created, created_ts, metadata_id, start, start_ts, mean, min, max, last_reset, last_reset_ts, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s,  ... 3933 characters truncated ... s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING statistics.id, statistics.id AS id__1]
[parameters: (None, 1706576410.577547, 28, None, 1706572800.0, 3195.232080623055, 1218.0, 10613.0, None, None, None, None, None, 1706576410.5778189, 29, None, 1706572800.0, 0.14725605999999997, 0.14725606, 0.14725606, None, None, None, None, None, 1706576410.5779796, 31, None, 1706572800.0, 5.8999999999999995, 5.9, 5.9, None, None, None, None, None, 1706576410.578151, 32, None, 1706572800.0, 31.89257960794444, 26.7, 38.6, None, None, None, None, None, 1706576410.5783548 ... 884 parameters truncated ... 69.3626, 69.3535, None, 1706576410.5904734, 492, None, 1706572800.0, 2.1000000000000005, 2.1, 2.1, None, None, None, None, None, 1706576410.5906467, 493, None, 1706572800.0, None, None, None, None, None, 4.6152, 4.6152, None, 1706576410.5908117, 499, None, 1706572800.0, None, None, None, None, None, 723.991, 0.25900000000001455, None, 1706576410.590975, 515, None, 1706572800.0, None, None, None, None, 1706554710.865161, 2.44160729999985, 627.3264551400002)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

**THIS WARNING
Logger: homeassistant.components.recorder.statistics
Source: components/recorder/statistics.py:477
Integration: Recorder (documentation, issues)
First occurred: January 29, 2024 at 5:00:10 PM (2 occurrences)
Last logged: 7:00:10 AM

Blocked attempt to insert duplicated statistic rows, please report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+recorder%22
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1062, "Duplicate entry '499-1706572800' for key 'ix_statistics_statistic_id_start_ts'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 139, in session_scope
    yield session
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 477, in compile_statistics
    modified_statistic_ids = _compile_statistics(
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 573, in _compile_statistics
    session.flush()  # populate the ids of the new StatisticsShortTerm rows
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
    return self._exec_insertmany_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2120, in _exec_insertmany_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 331, in _query
    self._do_get_result(db)
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 136, in _do_get_result
    self._result = result = self._get_result()
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/MySQLdb/cursors.py", line 363, in _get_result
    return self._get_db().store_result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry '499-1706572800' for key 'ix_statistics_statistic_id_start_ts'")
[SQL: INSERT INTO statistics (created, created_ts, metadata_id, start, start_ts, mean, min, max, last_reset, last_reset_ts, state, sum) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s), (%s, %s, %s,  ... 3933 characters truncated ... s), (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING statistics.id, statistics.id AS id__1]
[parameters: (None, 1706576410.577547, 28, None, 1706572800.0, 3195.232080623055, 1218.0, 10613.0, None, None, None, None, None, 1706576410.5778189, 29, None, 1706572800.0, 0.14725605999999997, 0.14725606, 0.14725606, None, None, None, None, None, 1706576410.5779796, 31, None, 1706572800.0, 5.8999999999999995, 5.9, 5.9, None, None, None, None, None, 1706576410.578151, 32, None, 1706572800.0, 31.89257960794444, 26.7, 38.6, None, None, None, None, None, 1706576410.5783548 ... 884 parameters truncated ... 69.3626, 69.3535, None, 1706576410.5904734, 492, None, 1706572800.0, 2.1000000000000005, 2.1, 2.1, None, None, None, None, None, 1706576410.5906467, 493, None, 1706572800.0, None, None, None, None, None, 4.6152, 4.6152, None, 1706576410.5908117, 499, None, 1706572800.0, None, None, None, None, None, 723.991, 0.25900000000001455, None, 1706576410.590975, 515, None, 1706572800.0, None, None, None, None, 1706554710.865161, 2.44160729999985, 627.3264551400002)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

**THIS ERROR
Logger: homeassistant.components.recorder.core
Source: components/recorder/core.py:901
Integration: Recorder (documentation, issues)
First occurred: January 29, 2024 at 5:00:10 PM (2 occurrences)
Last logged: 7:00:10 AM

Error while processing event StatisticsTask(start=datetime.datetime(2024, 1, 30, 0, 55, tzinfo=datetime.timezone.utc), fire_events=True): cannot access local variable 'modified_statistic_ids' where it is not associated with a value
Error while processing event StatisticsTask(start=datetime.datetime(2024, 1, 30, 14, 55, tzinfo=datetime.timezone.utc), fire_events=True): cannot access local variable 'modified_statistic_ids' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 901, in _guarded_process_one_task_or_recover
    self._process_one_task_or_recover(task)
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 912, in _process_one_task_or_recover
    return task.run(self)
           ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/tasks.py", line 165, in run
    if statistics.compile_statistics(instance, self.start, self.fire_events):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/util.py", line 625, in wrapper
    return job(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 481, in compile_statistics
    if modified_statistic_ids:
       ^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'modified_statistic_ids' where it is not associated with a value

**Comment by bsp9493** [comment]
this additional error also just showed up.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/eyeonwater/sensor.py:133
Integration: EyeOnWater (documentation)
First occurred: January 29, 2024 at 4:59:07 PM (72 occurrences)
Last logged: 10:45:23 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/eyeonwater/sensor.py", line 133, in _state_update
    if not self.meter._last_historical_data:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Meter' object has no attribute '_last_historical_data'

**Comment by kdeyev** [comment]
Hi @bsp9493 ,
Thank you for reporting.
Will look into it asap

**Comment by kdeyev** [comment]
@bsp9493 Do you still face this issue?
I was not able to understand what happened based on the call stack.

**Comment by bsp9493** [comment]
Clean boot, with 1.5 beta gives me this error.I don’t see any activity for today, but history appears to be there.This error originated from a custom integration.Logger: homeassistantSource: custom_components/eyeonwater/sensor.py:134Integration: EyeOnWater (documentation)First occurred: 11:04:06 AM (1 occurrences)Last logged: 11:04:06 AMError doing job: Task exception was never retrievedTraceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 276, in async_refresh    await self._async_refresh(log_failures=True)  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh    self.async_update_listeners()  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners    update_callback()  File "/config/custom_components/eyeonwater/sensor.py", line 134, in _state_update    if not self.meter._last_historical_data:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^AttributeError: 'Meter' object has no attribute '_last_historical_data'dOn Feb 4, 2024, at 10:33 AM, Konstantin Deev ***@***.***> wrote:﻿
@bsp9493 Do you still face this issue?
I was not able to understand what happened based on the call stack.

**Comment by kdeyev** [comment]
@bsp9493  Thank you! I found it, I introduced a typo while I dealt with logging in both v2.4.1 and v2.5.0-beta.1.
We saw that HA devs performed some refactoring around the statistics importing process, so we decided to get rid of the workaround we used on our end.
So if HA fixed the statistic problem: [2.4.2](https://github.com/kdeyev/eyeonwater/releases/tag/v2.4.2) should work.
[v2.5.0-beta.2](https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.0-beta.2) is the version with restored workaround, in case if HA did not fix the issue yet.
If you have issues with negative statistics in 2.4.2 - please let me know and I'll release https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.0-beta.2.
Thank you so much again for assisting with the development!

**Comment by bsp9493** [comment]
2.5.0 beta 2 appears to have sorted out the issues.No errors, no negatives.Looks good!dOn Feb 4, 2024, at 1:08 PM, Konstantin Deev ***@***.***> wrote:﻿
@bsp9493  Thank you! I found it, I introduced a typo while I dealt with logging in both v2.4.1 and v2.5.0-beta.1.
We saw that HA devs performed some refactoring around the statistics importing process, so we decided to get rid of the workaround we used on our end.
So if HA fixed the statistic problem: 2.4.2 should work.
v2.5.0-beta.2 is the version with restored workaround, in case if HA did not fix the issue yet.
If you have issues with negative statistics in 2.4.2 - please let me know and I'll release https://github.com/kdeyev/eyeonwater/releases/tag/v2.5.0-beta.2.
Thank you so much again for assisting with the development!

**Comment by kdeyev** [comment]
Released 2.5.0 officially.
Thank you!

**Comment by kdeyev** [comment]
Related to #30, addressed in v2.6.0 (beta on branch fix/negative-statistics-issue-30). Statistics now use async_add_external_statistics under eyeonwater: namespace - no more conflicts with HA's pipeline producing negative values.
